[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0F6CBD"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fb"
textColor = "#262626"
